const fs = require('fs-extra');
const path = require('path');
const https = require('https');
const { logInfo, logSuccess } = require('./logger');
const { installDevDependency } = require('./packageManager');

const SONAR_PROPS_FILE = 'sonar-project.properties';

// Default to local SonarQube — can be overridden by environment variables
// To use SonarCloud instead, set env vars:
//   SONAR_HOST_URL=https://sonarcloud.io
//   SONAR_TOKEN=<your_sonarcloud_token>
//   SONAR_ORG=<your_org>
const SONAR_HOST_URL = process.env.SONAR_HOST_URL || 'http://secure-suite.ddns.net:9000';
const SONAR_TOKEN    = process.env.SONAR_TOKEN    || '';
const SONAR_ORG      = process.env.SONAR_ORG      || '';

// Auto-create project on SonarCloud via API so developer never needs to do it manually
async function ensureProjectExists(projectKey, projectName) {
  return new Promise((resolve) => {
    const auth = Buffer.from(`${SONAR_TOKEN}:`).toString('base64');
    const postData = `name=${encodeURIComponent(projectName)}&project=${encodeURIComponent(projectKey)}&organization=${encodeURIComponent(SONAR_ORG)}`;

    const options = {
      hostname: 'sonarcloud.io',
      port: 443,
      path: '/api/projects/create',
      method: 'POST',
      headers: {
        'Authorization': `Basic ${auth}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': Buffer.byteLength(postData)
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode === 200 || res.statusCode === 201) {
          logSuccess(`SonarQube project "${projectKey}" created automatically.`);
        } else if (res.statusCode === 400 && data.includes('already exists')) {
          logInfo(`SonarQube project "${projectKey}" already exists.`);
        } else {
          logInfo(`SonarQube project setup: ${res.statusCode} — continuing anyway.`);
        }
        resolve();
      });
    });

    req.on('error', (err) => {
      logInfo(`SonarQube server unreachable — skipping project creation. (${err.message})`);
      resolve();
    });

    req.write(postData);
    req.end();
  });
}

exports.installSonarScanner = async () => {
  logInfo('Installing sonarqube-scanner as a dev dependency...');
  await installDevDependency('sonarqube-scanner');
  logSuccess('sonarqube-scanner installed.');
};

exports.setupSonarProperties = async () => {
  const propsPath = path.join(process.cwd(), SONAR_PROPS_FILE);

  const pkgPath = path.join(process.cwd(), 'package.json');
  let projectKey  = 'my-project';
  let projectName = 'My Project';

  if (await fs.pathExists(pkgPath)) {
    const pkg = await fs.readJSON(pkgPath);
    if (pkg.name) {
      projectKey  = pkg.name.replace(/[^a-zA-Z0-9_\-.:]/g, '_');
      projectName = pkg.name;
    }
  }

  logInfo(`Setting up SonarQube project "${projectKey}"...`);

  // Build org line only if one is configured (needed for SonarCloud, not local SonarQube)
  const orgLine = SONAR_ORG ? `sonar.organization=${SONAR_ORG}` : '# sonar.organization=   # Uncomment and set this only for SonarCloud';
  // Use sonar.login for compatibility with SonarQube 9.x and 10.x (sonar.token only works on 10+)
  const tokenLine = SONAR_TOKEN ? `sonar.login=${SONAR_TOKEN}` : 'sonar.login=REPLACE_WITH_YOUR_SONAR_TOKEN';

  const content = `# ---------------------------------------------------------------
# SonarQube configuration — auto-generated by secure-husky-setup
# Pointing to secure-suite.ddns.net:9000 by default
# To use SonarCloud: change sonar.host.url and set sonar.token + sonar.organization
# ---------------------------------------------------------------
sonar.host.url=${SONAR_HOST_URL}
${tokenLine}
${orgLine}
sonar.projectKey=${projectKey}
sonar.projectName=${projectName}
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,.husky/**,.tools/**
`;

  await fs.writeFile(propsPath, content);
  logSuccess(`${SONAR_PROPS_FILE} configured.`);
  if (!SONAR_TOKEN) {
    logInfo('ACTION REQUIRED: Open sonar-project.properties and replace REPLACE_WITH_YOUR_SONAR_TOKEN with a real token from http://secure-suite.ddns.net:9000 → My Account → Security → Generate Token');
  }
};